### PR TITLE
Add MQ REQ sensor_history.get: get the filtered and calculated histor…

### PR DESCRIPTION
**Pull request by vdomos**
Add MQ REQ sensor_history.get: 
Get the filtered and calculated history starting from/to a certain timestamp.
Like REST functions sensorHistory_from_filter and sensorHistory_from_to_filter

See "src/domogik/examples/mq-python/req_sensor_history.py" example #4 for usage.

### CODE REVIEW

**Comment by fritz-smh** [comment]
What does the 'filter' thing ? 
Can you give ma a use case ?

**Comment by vdomos** [comment]
It's the same as REST SensorHistory - Retrieve the filtered and calculated history starting from a certain timestamp
http://apidoc.domogik.org/rest/#api-SensorHistory-getSensorHistoryFilter
http://apidoc.domogik.org/rest/#api-SensorHistory-getSensorHistoryFilter2

it's for use in plugin or advanced page.
It is an old demand for evolution which I thought: https://github.com/domogik/domogik/issues/290

As the use of REST is deprecated in the plugin, I thought it would be a good idea to include it in the MQ

No ?

**Comment by fritz-smh** [comment]
ok for me :)
Could you add also a python sample code to use it in src/domogik/examples/mq-python ?

**Comment by vdomos** [comment]
Already done in the PR ;)
https://github.com/domogik/domogik/pull/519/files#diff-979fb570b1fff6ff27343feefb5cac59

**Comment by fritz-smh** [comment]
I missed it !

**Pull request merged**
