### PR TITLE
Logging #219

### PR DESCRIPTION
**Pull request by tikismoke**
Add a default log prefix to plugin and change for core one

### CODE REVIEW

**Comment by tikismoke** [comment]
Or we can also add prefix in all plugins init.

**Comment by fritz-smh** [comment]
missing xplgw I think in core list

**Comment by tikismoke** [comment]
Will look this afternoon. Do you think it's thé right way or shoul We do this un plugin only

**Comment by fritz-smh** [comment]
not on each plugin side ;)

**Comment by tikismoke** [comment]
In bin:
dump_xpl use XplPlugin class without log_prefix (log_prefix = "xplplugin_")
manager use XplPlugin class with log_prefix=""
send use XplPlugin class without log_prefix (log_prefix = "xplplugin_")
xplgw use XplPlugin class with log_prefix=""
in interface:
use Plugin class with prefix log_prefix = "interface_"
In tests:
rfxcom_lan use xplplugin class without log_prefix  (log_prefix = "xplplugin_")
xpl_client use xplplugin class without log_prefix (log_prefix = "xplplugin_")


Now looking to correct travis ;)

**Comment by tikismoke** [comment]
Ok find one in travis-after.sh

**Pull request merged**
