### PR TITLE
Fix #153, conversion map refreshed on xplgw

### LINKED ISSUE #153: Conversion map could be empty on xplgw
If mq fail on response when xplgw start (__init__)
Conversion map was empty. 
So impossible to convert valeur before db store. 
This create issue for stat  and command

### PR DESCRIPTION
**Pull request by Nico0084**
Resolve on adding a dynamic refresh on class _SensorThread for client_conversion maps

### CODE REVIEW

**Comment by fritz-smh** [comment]
Hi,

So this is a fix for 0.4.2 ?
If so, we should do the merge in a dedicated branch.

Master should not be used for fix as we did for 0.4.2, this was a big error :)

Waiting for your response and then, I will create a 0.4 fix branch

Fritz

**Comment by Cereal2nd** [comment]
This is indeed a good fix

and it should go into a dedicated branch to be included in the next 0.4
release

**Comment by fritz-smh** [comment]
I will create the branch this morning and then cancel this PR

Nico, you will have to create a new PR for the new branch ;)

**Comment by fritz-smh** [comment]
Here is the branch : https://github.com/domogik/domogik/tree/0.4-hotfix

I close this PR and let you open the new one on this branch

**Pull request closed without merging**
