### PR TITLE
Plugin dev tools

### PR DESCRIPTION
**Pull request by Nico0084**
Additional tools for developper to handling devices in plugin, Update doc too.

### CODE REVIEW

**Comment by Cereal2nd** [comment]
first fix the travis build, then we will have a look at it

**Comment by Nico0084** [comment]
Travis build passed :)

**Comment by Cereal2nd** [comment]
hmm, looked at the code and tested it a bit.
I like this one. Just not sure why you would need the def udpate_device_param function?

why do you need this for a device?

**Comment by Nico0084** [comment]
Hi,
I use def udpate_device_param function in advanced admin to set a global
param who check battery level,
So user don't need to edit device :)
[image: Images intégrées 1]

2016-10-18 10:33 GMT+02:00 Maikel Punie <notifications@github.com>:

**Comment by fritz-smh** [comment]
Very very nice.
On my side I am ok to merge this in develop

And there is the doc :). Really great!

**Pull request merged**
